### ISSUE TITLE
Ресёрч-док

### ISSUE THREAD

**Issue by oryce** [oryce/mai-ck#1]
Требования к содержанию:

- название материала
- авторы
- ссылка на материал
- краткая информация что удалось получить от этого материала

Draft: https://docs.google.com/document/d/1wPYW-hs8H9Sqlf3-yUqs9YxoY2p-NNjD7AQ5vdhJ0Tw/edit?usp=sharing

**Comment by ArtemDelGray** [comment]
[ЦК1.pptx](https://github.com/user-attachments/files/18140394/1.pptx)

Сделал без Архитектуры решения, вставил пока случайный образец.
