### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by oryce** [oryce/mai-ck#3]
Диаграмма, описывающая поведение пользователей. 
 
- https://ru.wikipedia.org/wiki/Сценарий_использования
- https://en.wikipedia.org/wiki/Use_case_diagram
- https://ru.wikipedia.org/wiki/Диаграмма_прецедентов
- https://shesterov.by/tpost/g9mg3zhpi1-uml-use-case-diagram

Шаблон: https://miro.com/templates/use-case-diagram/

**Comment by kalane15** [comment]
что то накидал, хз то это или не то, в общем чекните, надо ли еще что то делать:
https://miro.com/app/board/uXjVL4kRbQE=/
