### ISSUE TITLE
Диаграмма контекста, диаграмма компонентов

### ISSUE THREAD

**Issue by oryce** [oryce/mai-ck#4]
## Диаграмма контекста

- https://en.wikipedia.org/wiki/System_context_diagram
- https://miro.com/blog/context-diagram/

Шаблон: https://miro.com/templates/context-diagram/

## Диаграмма компонентов 

- https://en.wikipedia.org/wiki/Component_diagram
- https://ru.wikipedia.org/wiki/Диаграмма_компонентов

Шаблон: https://miro.com/templates/uml-component-diagram/

**Comment by nik575sav** [comment]
![Untitled Diagram drawio](https://github.com/user-attachments/assets/8993b11e-379a-40e9-82bb-f6f7dbfbe3e7)

**Comment by nik575sav** [comment]
![Diagram of context](https://github.com/user-attachments/assets/fda622b2-8478-45ef-b978-db6e9ab9cb2c)
