### ISSUE TITLE
Презентация проекта

### ISSUE THREAD

**Issue by oryce** [oryce/mai-ck#5]
Оформить как презентацию:

1. Анализ существующих решений (research-doc)
2. Список команды с ролями
3. Цель и задачи
4. Use cases
5. Диаграмма контекстов
6. Диаграмма компонентов

**Comment by ArtemDelGray** [comment]
[ЦК1.pptx](https://github.com/user-attachments/files/18140398/1.pptx)
Сделал пока без Архитектуры решения. Вставил случайный образец.

**Comment by ArtemDelGray** [comment]
[ЦК2.pptx](https://github.com/user-attachments/files/18140458/2.pptx)
Обновил текст, добавил переход.

**Comment by ArtemDelGray** [comment]
[ЦК2.pptx](https://github.com/user-attachments/files/18141217/2.pptx)
Отредактировал архитектуру
